"""add relationships

Revision ID: 742300801522
Revises: a9547a95ac4a
Create Date: 2024-07-13 12:44:56.213502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742300801522'
down_revision = 'a9547a95ac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_customer_id_customers'), 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_item_id_items'), 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_item_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_customer_id_customers'), type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
