"""add date

Revision ID: 968be34f7452
Revises: a26a4a9fed8d
Create Date: 2024-07-21 14:12:18.102307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968be34f7452'
down_revision = 'a26a4a9fed8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
